remote_theme: daviddarnes/alembic

navigation_header:
  Home: /
  Project 1: /project1_bamap/project1.html
  Project 2: /project2_sfi/project2.html
  Project 3: /project1_bamap/project1.html
  Project 4: /project1_bamap/project1.html

@import url('https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,700');
@import url('https://fonts.googleapis.com/css?family=Source+Code+Pro:400,700');